---
title: "Movie Data"
author: "Pete Mohanty"
output: github_document
---

```{r, echo=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, comment="")
```

```{r}
library(kerasformula)
library(ggplot2)

movies <- read.csv("http://s3.amazonaws.com/dcwoods2717/movies.csv")
dplyr::glimpse(movies)

```

## Predicting Profitability

Suppose we are interested in revenue relative to budget... Since `y = log10(gross/budget)`, `y = 0` means "break even."
```{r, echo=FALSE}
ggplot(movies, aes(log10(gross/budget))) + geom_density() + theme_minimal() + labs(title = "Forecasting Movies' Financial Success", 
                         subtitle = "Source data: http://s3.amazonaws.com/dcwoods2717/movies.csv")
```
Let's predict `log10(gross/budget)`. The logged data look approximately normal.
```{r}
f <- formula(log10(gross/budget) ~ . -genre -director -title)
P <- ncol(model.matrix(f, movies))
out <- kms(f, movies, seed=1234, batch_size = 1)
out$MAE_predictions
out$R2_predictions
est <- data.frame(y = c(out$y_test, out$predictions),
           type = c(rep("y_test", length(out$y_test)), rep("predictions", length(out$predictions))))
ggplot(est, aes(x=y, fill=type)) + geom_histogram()
```

```{r}
library(polyreg)
xy <- cbind(movies[,c(4:5, 8:11)])
xy <- cbind(xy, log10(movies$gross/movies$budget))
xval.out <- xvalPoly(xy, maxDeg = 3, maxInteractDeg = 2)
xval.out

```

